config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end

  root 'home#index'

  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'


  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'

  namespace :admin do
    resources :dashboard, only: [:index]

    namespace :users do

      resources :users, param: :username do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end

        member do
          post 'revert_removal', as: :revert_removal
          post 'block', as: :block
          post 'revert_block', as: :revert_block
          post 'suspect', as: :suspect
          post 'revert_suspect', as: :revert_suspect
        end
      end

      resources :filters

      scope(':username') do
        resources :dashboard, only: [:index]

        resources :preferences, only: [:index]

        resources :notifications, only: [:index]

        resources :permissions, only: [:index]

        resources :logs, only: [:index, :show]
      end
    end

    scope module: 'sites' do

      resources :sites, param: :site_uid

      scope('sites/:site_uid') do
        patch 'edit', to: 'sites#update', as: :site_update

        resources :api_keys
        resources :trusted_domains
      end

    end

    # resources :settings, only: [:index]
    get 'settings/index', as: :settings
    post 'settings/update', as: :update_settings

  end

  namespace :users do

    get 'sessions/new'

    get 'user/edit' => 'users#edit', as: :edit

    patch 'user' => 'users#update', as: :update

    delete 'user' => 'users#destroy', as: :destroy

    resources :users, except: [:show, :edit, :update, :destroy] do
      collection do
        get 'check_username', as: :check_username
      end
    end

    # /!\ order has importance here
    # if we want default actions  not to be considered as a username
    # please let this line after other 'users' routes
    get 'user/:username' => 'users#show', as: :show


    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]

    resources :preferences, only: [:index]

    resources :notifications, only: [:index] do
      collection do
        get 'unread_all'
      end
    end
  end # namespace users

  #omniauth
  match '/auth/:provider/callback', to: 'users/omniauth#callback', via: :all
  match '/auth/failure', to: 'users/omniauth#failure', via: :all
  match '/auth/:token', to: 'users/omniauth#complete_profile', via: :get, as: :auth_complete_profile
  match '/auth/:token', to: 'users/omniauth#finalize', via: :post, as: :auth_finalize

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          put :update
          get '/show' => 'users#show'
        end
      end
      resources :tokens, only: [:create] do
        collection do
          put :update
        end
      end
      resources :oauth_providers, only: [:index]
      resources :conversations, only: [:show], param: :identifier
    end #v1
  end # namespace api

  namespace :client do
    get '/' =>'home#index', as: :home
  end
end

app/controllers/admin/users/dashboard_controller.rb
class Admin::Users::DashboardController < Admin::AdminController
  include Admin::Users::UsersHelper
  
  before_action :identify_user
  
  def index
  end
end

app/controllers/admin/users/filters_controller.rb
class Admin::Users::FiltersController < Admin::AdminController
  before_action :load_filters, only: [:index]
  before_action :set_filter, only: [:destroy]
  
  def index
    
  end
  
  def create
    @filter = UserFilter.new(filter_params)
    
    @filter.blocked = true
    
    @filter.save
  end
  
  
  def destroy
    
    @filter.destroy
    
  end
  
  private
  
  def load_filters
    @all_blocked = UserFilter.all_blocked
  end
  
  def set_filter
    @filter = UserFilter.find_by_id(params[:id])
  end
  
  def filter_params
    params.require(:user_filter).permit( :ip_address, 
      :email_provider )
  end
end

app/controllers/admin/users/logs_controller.rb
class Admin::Users::LogsController < Admin::AdminController
  include Admin::Users::UsersHelper
  
  before_action :identify_user
  
  def index
    logs = @user.logs.recent.paginate(page: params[:page])

    render :locals => { :user => @user, :logs => logs }
  end
  
  def show
    log = Log.find_by_id(params[:id])
    
    render :locals => { :log => log }
  end
end

app/controllers/admin/users/notifications_controller.rb
class Admin::Users::NotificationsController < Admin::AdminController
  include Admin::Users::UsersHelper
  
  before_action :identify_user
  
  def index
    notifications = @user.notifications.order(:created_at => :DESC).paginate(page: params[:page])
    
    render locals: { notifications: notifications }
  end
end

app/controllers/admin/users/permissions_controller.rb
class Admin::Users::PermissionsController < Admin::AdminController
  include Admin::Users::UsersHelper
  
  before_action :identify_user
  
  def index
  end
end

app/controllers/admin/users/preferences_controller.rb
class Admin::Users::PreferencesController < Admin::AdminController
  include Admin::Users::UsersHelper
  
  before_action :identify_user
  
  def index
  end
end

app/controllers/admin/users/users_controller.rb
class Admin::Users::UsersController < Admin::AdminController
  include Admin::Users::UsersHelper

  before_action :identify_user, except: [:index, :search]

  before_action :prevent_only_admin_removal, only: :destroy

  before_action :load_settings, only: [ :new, :create, :edit, :update ]

  respond_to :html, :js

  def index
    params[:list] ||= 'active'

    @users = users_selection(params[:list]).paginate(page: params[:page])

    render locals: { users: @users, list: params[:list] }
  end


  def search
    params[:search] ||= ""

    min_characters = 3
    max_characters = 50

    unless (min_characters..max_characters).include?(params[:search].length)
      flash.now[:warning] = t('admin.users.users.search.notice.length-must-be-in-interval',
        :min => min_characters,
        :max => max_characters)

      @users = User.none.paginate(page: params[:page])
    else
      @users = User.search( params[:search] ).paginate(page: params[:page])
    end

    render :index, locals: { users: @users, list: nil, search: params[:search] }
  end


  def show
    redirect_to admin_users_dashboard_index_path(params[:username])
  end


  def edit
    @user.build_avatar if @user.avatar.nil?

    render :edit, locals: { user: @user }
  end


  def update
    if @user.active? && @user.update_attributes(user_update_params)
      flash[:success] = t 'user.notice.success.updated'
      redirect_to edit_admin_users_user_path
    else
      render :edit, locals: { user: @user }
    end
  end

  def block
    options = {}

    options[:blocked_note] = params['user']['blocked_note'] if params['user'].present?

    if @current_user.block_user(@user, options)
      flash[:success] = t 'user.notice.success.block'
    else
      flash[:danger] = t 'user.notice.danger.block'
    end

    redirect_to edit_admin_users_user_path
  end

  def revert_block
    if @current_user.unblock_user(@user)
      flash[:success] = t 'user.notice.success.revert-block'
    else
      flash[:danger] = t 'user.notice.danger.revert-block'
    end

    redirect_to edit_admin_users_user_path
  end

  def suspect
    options = {}

    options[:suspected_note] = params['user']['suspected_note'] if params['user'].present?


    if @current_user.suspect_user(@user, options)
      flash[:success] = t 'user.notice.success.suspect'
    else
      flash[:danger] = t 'user.notice.danger.suspect'
    end

    redirect_to edit_admin_users_user_path
  end

  def revert_suspect
    if @current_user.trust_user(@user)
      flash[:success] = t 'user.notice.success.revert-suspect'
    else
      flash[:danger] = t 'user.notice.danger.revert-suspect'
    end

    redirect_to edit_admin_users_user_path
  end

  def revert_removal
    if @user.present? && @user.deactivated?
      @user.revert_removal
      flash[:success] = t 'user.notice.success.removal-reverted'
    else
      flash[:warning] = t 'user.notice.warning.removal-revert-failed'
    end

    redirect_to edit_admin_users_user_path
  end

  def destroy
    @user.destroy

    flash[:success] = t 'user.notice.success.destroyed'

    redirect_to :admin_users_users
  end


  private


  def prevent_only_admin_removal
    if @user.admin? && !User.admins.many?
      flash[:danger] = t('user.notice.danger.only-admin-removal')
      redirect_to :admin_users_users
    end
  end

  def find_user
    @user = User.find(params[:id])
  end

  def load_settings
    @removal_delay = User.removal_delay_duration
  end

  def users_selection(kind)
    case kind
      when 'new' then User.newest
      when 'staff' then User.staff
      when 'blocked' then User.all_blocked
      when 'suspected' then User.suspects
      when 'deactivated' then User.all_deactivated
      when 'to_be_deleted' then User.all_to_be_deleted
      else User.all_valid.where(suspected: false)
    end
  end

  def user_update_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation,
      :locale,
      :description,
      avatar_attributes: [:kind, :uri, :uri_cache]
      )
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  include ApplicationHelper
  skip_before_action :authorize_request, only: :create
  skip_before_action :authenticate_site, only: [:create, :update, :show]

  def create
    @user = User.new( user_create_params.merge({
                                                    creation_ip_address: request.remote_ip,
                                                    creation_domain: request.host + request.port_string,
                                                    locale: detect_language
                                                  }) )

    if Users::ConcernedByFiltersService.new(@user).call
      @user.errors.add(:base, I18n.t('user.notice.danger.invalid-login'))
    elsif params[:client_platform].blank?
      @user.errors.add(:base, I18n.t('user.notice.danger.client-platform-required'))
    end

    if @user.errors.empty? && @user.save
      refresh_token = Users::ObtainRefreshTokenService.new(@user, client_platform).call
      options = { client_platform: client_platform, refresh_token: refresh_token.try(:token) }

      if client_platform == WEB_CLIENT
        cookies['token'] = { :value => @user.api_access_token, :httponly => true }
        options[:csrf_token] = Users::GenerateCsrfTokenService.new(@user).call
      end

      render_success(@user, :created, **options)
    else
      render_error(@user, :unprocessable_entity)
    end
  end

  def update
    unless @current_user.active?
      @current_user.errors.add(:base, I18n.t('user.notice.danger.invalid-login'))
    end

    if @current_user.errors.empty? && @current_user.update_attributes(user_update_params)
      render_success(@current_user, :ok, hide_tokens: true)
    else
      render_error(@current_user, :unprocessable_entity)
    end
  end

  def show
    render_success(@current_user, :ok)
  end

  private

  def user_create_params
    params.permit(
        :username,
        :email,
        :password,
        :password_confirmation,
        :time_zone
    )
  end

  def user_update_params
    params.permit(
      :username,
      :email,
      :password,
      :password_confirmation,
      :time_zone,
      :locale,
      :description
    )
  end
end

app/controllers/users/account_activations_controller.rb
class Users::AccountActivationsController < ApplicationController

  def edit
    @user = User.all_valid.find_by(email: params[:email])
      
    if @user &&
      !@user.activated? &&
      @user.authenticated?(:activation, params[:id])
        @user.activate(request.remote_ip )
        
        log_in @user
        flash[:success] = t('user.notice.success.account-activated')
          
        redirect_to users_dashboard_index_url
    else
      flash[:danger] = t('user.notice.danger.invalid-activation-link')
        
      redirect_to root_url
    end
  end

end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  
  protected
  
  def use_current_user
    @user = @current_user
  end
  
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  
  def index
    
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < Users::BaseController
  before_action :logged_in_user
  before_action :use_current_user
  
  def index
    notifications = @user.notifications.order(:created_at => :DESC).paginate(page: params[:page])
    
    render locals: { notifications: notifications }
  end
  
  def unread_all
    @user.notifications.unread.update_all( read: true )
    
    
  end
end

app/controllers/users/omniauth_controller.rb
require 'redis_connect'

class Users::OmniauthController < ApplicationController
  include ApplicationHelper
  include Users::OmniauthHelper

  skip_before_action :verify_authenticity_token, only: :callback
  before_action :use_cache_infos, only: [:complete_profile, :finalize]

  COMPLETION_TOKEN_EXP = 10.minutes.to_i.freeze
  COMPLETION_TOKEN_RETRY = 3.freeze

  def callback
    auth = request.env['omniauth.auth']
    params = request.env['omniauth.params']
    infos = auth.fetch(:info, {})
    from = params.fetch('from', nil)
    account = AuthAccount.find_or_initialize_by(uid: auth['uid'],provider: auth['provider'])

    if account.user.present?
      unless account.user.active?
        account.user.log(:auth_login_fail_not_active)
        flash[:warning] = t('user.notice.warning.account-not-activated')

        if from == 'client'
          render layout: 'empty_hd'
        else
          redirect_to root_url and return
        end
      end
      if from == 'client'
        flash[:success] = t('omniauth.client.notice.success')
        gain_access_on_client(account.user)
        render layout: 'empty_hd'
      else
        log_in account.user
        redirect_to root_url
      end
    elsif account.save
      redis = RedisConnect.new
      token = nil
      cache_infos = {
        id: account.id,
        from: from,
        email: infos[:email],
        img: infos[:image]
      }

      COMPLETION_TOKEN_RETRY.times do
        token = SecureRandom.hex
        break if redis.hadd(token, cache_infos, ex: COMPLETION_TOKEN_EXP)
        token = nil
      end

      if token.nil?
        flash[:danger] = t('user.notice.warning.auth-completion-fail-no-token')
        if from == 'client'
          render layout: 'empty_hd'
        else
          redirect_to root_url and return
        end
      end

      account.update_attributes(name: infos['name'], nickname: infos['nickname'])

      redirect_to auth_complete_profile_url(
                    token: token,
                    auth_email: (infos['email'].present?) ? 1 : 0,
                    auth_img: (infos['image'].present?) ? 1 : 0
                  )
    else
      redirect_to :auth_failure_url
    end
  end

  def complete_profile
    @username =  (@account.nickname || @account.name).parameterize
    @user = User.new
    render layout: 'empty_hd'
  end

  def finalize
    @username = params[:username]
    password = SecureRandom.base64
    @user = User.new(
      username: @username,
      auth_account: @account,
      creation_ip_address: request.remote_ip,
      creation_domain: request.host + request.port_string,
      locale: detect_language,
      password: password,
      password_confirmation: password
    )

    @user.email = @cache_infos['email'] if params[:use_email] == '1'

    unless @user.save
      render 'complete_profile', layout: 'empty_hd' and return
    end

    @user.activate(request.remote_ip )

    if params[:use_img] == '1'
      @user.avatar = UserAvatar.new( kind: :upload )
      @user.avatar.uri.download!(@cache_infos['img'])
      @user.avatar.save
    end

    if @cache_infos['from'] == 'client'
      gain_access_on_client(@user)
      flash[:success] = t('omniauth.client.notice.success')
      render 'callback', layout: 'empty_hd'
    else
      log_in @account.user

      flash[:success] = t('user.notice.success.first-login', username: @user.username)
      redirect_to root_url
    end
  end

  def failure
    flash[:danger] = t('user.notice.danger.auth-failure')
    redirect_to root_url and return
  end

  private

  def use_cache_infos
    redis = RedisConnect.new

    @cache_infos = redis.hgetall(params[:token])

    unless @cache_infos != nil && @account = AuthAccount.without_user.find_by_id(@cache_infos['id'])
      flash[:warning] = t('user.notice.warning.auth-cache-not-found')
      redirect_to root_url and return
    end
  end
end

app/controllers/users/preferences_controller.rb
class Users::PreferencesController < ApplicationController
end

app/helpers/admin/users/filters_helper.rb
module Admin::Users::FiltersHelper
end

app/helpers/admin/users/users_helper.rb
module Admin::Users::UsersHelper
  
  def identify_user
    @user = User.where(username_lower: params[:username]).first
    
    redirect_to :admin_users_users if @user.nil?
  end
  
end

app/views/admin/users/users/_blocked_list_body.html.erb
<% present(user) do |user| %>
<tr>
  <td><%= user.avatar_thumbnail_tag(size: 50) %></td>
  <td><%= link_to user.username, admin_users_dashboard_index_path(user.username_lower) %></td>
  <td><%= user.email %></td>
  <td><%= distance_of_time_in_words_to_now(user.last_seen_at) %></td>
  <td><%= l user.blocked_at, format: :short %></td>
</tr>
<% end %>

app/views/admin/users/users/_default_list.html.erb
<div class="container">

  <div class="row">
      <div class="col-md-10">
        <nav class="nav nav-inline">
          <% active = (list == "active") ? "active" : "" %>
          <%= link_to t('admin.users.users.index.tab.active-filter'), list_admin_users_users_path(:list => 'active'), class: "nav-link #{active}" %>

          <% active = (list == "new") ? "active" : "" %>
          <%= link_to t('admin.users.users.index.tab.new-filter'), list_admin_users_users_path(:list => 'new'), class: "nav-link #{active}" %>

          <% active = (list == "staff") ? "active" : "" %>
          <%= link_to t('admin.users.users.index.tab.staff-filter'), list_admin_users_users_path(:list => 'staff'), class: "nav-link #{active}" %>
        </nav>
      </div>
  </div>

  <div class="row">
    <%= will_paginate users , :previous_label => '', :next_label => '' %>

    <table class="table table-striped">
      <thead>
      <tr>
        <th></th>
        <th><%= t 'admin.users.users.index.username' %></th>
        <th><%= t 'admin.users.users.index.email' %></th>
        <th><%= t 'admin.users.users.index.last-seen' %></th>
        <th><%= t 'admin.users.users.index.created-at' %></th>
      </tr>
      </thead>
      <tbody>
      <%= render users %>
      </tbody>
    </table>

    <%= will_paginate users, :previous_label => '', :next_label => '' %>
  </div>
</div>

app/views/admin/users/users/_form.html.erb
<% content_for :header do %>
  <%= javascript_include_tag 'admin/users/user' %>
  <%= stylesheet_link_tag 'users/user' %>
<% end %>

<% present(user) do |user| %>
  <%= form_for [:users, user], { :url => admin_users_user_path } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :avatar %>
    <div class="row">
      <div class="col-md-2">
        <div id="avatar-thumbnail">
          <%= user.avatar_thumbnail_tag %>
        </div>
      </div>
      <div class="col-md-6">

        <%= f.fields_for :avatar do |a| %>
        <%= a.select :kind, UserAvatar.kinds.keys.map {|kind| [kind.titleize,kind]}, {}, { class: 'form-control' } %>

          <%= a.file_field :uri, class: 'form-control', style: (user.avatar.upload?) ? '' : 'display:none' %>

          <%= a.hidden_field :uri_cache %>
        <% end %>

      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <%= f.label :username %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <%= f.text_field :username, class: 'form-control' %>
      </div>
      <div id="notice-username" class="col-md-4 col-notice"></div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <%= f.label :email %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div id="notice-email" class="col-md-4 col-notice"></div>
    </div>


      <div class="row">
        <div class="col-md-8">
          <%= f.label :description %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= f.text_area :description, class: 'form-control' %>
          <p class="text-muted"><small><%= t 'user.form.help-text.description' %></small></p>
        </div>
        <div class="col-md-4 col-notice"></div>
      </div>


      <div class="row">
        <div class="col-md-8">
          <%= f.label :locale %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= f.select :locale, I18n.available_locales.map {|l| [l.to_s.capitalize_first,l]}, {}, { class: 'form-control' } %>
        </div>
        <div class="col-md-4 col-notice"></div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= f.label :password %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div id="notice-password" class="col-md-4 col-notice"></div>
      </div>


      <div class="row">
        <div class="col-md-8">
          <%= f.label :password_confirmation %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="col-md-4 col-notice"></div>
      </div>

      <div class="row row-section">
        <div class="col-md-8">
          <% if user.deactivated? %>
            <%= button_tag t('admin.users.users.edit.revert-removal'),
              class: "btn btn-block btn-sm btn-primary",
              type: "button",
              data: {toggle: "modal",target: "#revertModal"}
            %>
          <% else %>
            <%= f.submit  t('user.form.edit.submit'), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>

      <div class="row row-section">
        <div class="col-md-8">
          <% unless user.blocked? %>
              <%= button_tag t('admin.users.users.edit.block'),
                class: "btn btn-block btn-sm btn-primary-outline",
                type: "button",
                data: {toggle: "modal",target: "#blockModal"}
              %>
          <% else %>
              <%= button_tag t('admin.users.users.edit.revert-block'),
                class: "btn btn-block btn-sm btn-primary-outline",
                type: "button",
                data: {toggle: "modal",target: "#revertBlockModal"}
              %>
          <% end %>
        </div>
      </div>

      <% unless user.blocked? %>
        <div class="row row-section">
          <div class="col-md-8">
            <% unless user.suspected? %>
                <%= button_tag t('admin.users.users.edit.suspect'),
                  class: "btn btn-block btn-sm btn-primary-outline",
                  type: "button",
                  data: {toggle: "modal",target: "#suspectModal"}
                %>
            <% else %>
                <%= button_tag t('admin.users.users.edit.revert-suspect'),
                  class: "btn btn-block btn-sm btn-primary-outline",
                  type: "button",
                  data: {toggle: "modal",target: "#revertSuspectModal"}
                %>
            <% end %>
          </div>
        </div>
      <% end %>

      <% if user.blocked? %>
        <div class="row row-section">
          <div class="col-md-8">
              <%= button_tag t('admin.users.users.edit.unblock-suspect'),
                class: "btn btn-block btn-sm btn-primary-outline",
                type: "button",
                data: {toggle: "modal",target: "#suspectModal"}
              %>
          </div>
        </div>
      <% end %>

      <% if !user.deactivated? || user.removable? %>
        <div class="row row-section">
          <div class="col-md-8">
            <%
            rm_label = if user.to_be_deleted? then t('admin.users.users.edit.destroy-now')
            elsif user.deactivated? then t('admin.users.users.edit.destroy-data')
            else t('admin.users.users.edit.destroy')
            end
            %>

            <%= button_tag rm_label,
              class: "btn btn-block btn-sm btn-danger-outline",
              type: "button",
              data: {toggle: "modal",target: "#removalModal"}
            %>
          </div>
        </div>
      <% end %>
  <% end %>

  <%= render 'modal_removal', user: user %>
  <%= render 'modal_revert_removal', user: user %>
  <%= render 'modal_block', user: user %>
  <%= render 'modal_suspect', user: user %>
  <%= render 'modal_revert_block', user: user %>
  <%= render 'modal_revert_suspect', user: user %>

<% end %>

app/views/admin/users/users/_modal_block.html.erb
<!-- Modal -->
<div class="modal fade" id="blockModal" tabindex="-1" role="dialog" aria-labelledby="blockModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :user, url: block_admin_users_user_path, method: :post do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="blockModalLabel"><%= t('admin.users.users.block-modal.title') %></h4>
        </div>
        <div class="modal-body">
            <%= simple_format t("admin.users.users.block-modal.notice") %>
            
            <div class="row">
              <div class="col-md-12">
                <%= f.label :blocked_note %>
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-12">
                <%= f.text_area :blocked_note, class: 'form-control' %>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <%= button_tag t('admin.users.users.block-modal.close'), class: 'btn btn-default', 'type': 'button', 'data-dismiss': "modal" %>
          <%= button_tag t('admin.users.users.block-modal.submit'), class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/admin/users/users/_modal_removal.html.erb
<!-- Modal -->
<div class="modal fade" id="removalModal" tabindex="-1" role="dialog" aria-labelledby="removalModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :user, url: admin_users_user_path, method: :delete do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="removalModalLabel"><%= t('admin.users.users.removal.title') %></h4>
        </div>
        <div class="modal-body">
          <% if user  == @current_user %>
            <div class="alert alert-warning" role="alert"><%= t("admin.users.users.removal.yourself-notice") %></div>
          <% elsif user.admin? %>
            <div class="alert alert-warning" role="alert"><%= t("admin.users.users.removal.admin-notice") %></div>
          <% end %>

          <% if user.deactivated? %>
            <%= simple_format t("admin.users.users.removal.method-notices.perform") %>
          <% else %>
            <%= simple_format t("admin.users.users.removal.method-notices.delay", days: @removal_delay) %>
          <% end %>
        </div>
        <div class="modal-footer">
          <%= button_tag t('admin.users.users.removal.close'), class: 'btn btn-default', 'type': 'button', 'data-dismiss': "modal" %>
          <%= button_tag t('admin.users.users.removal.remove'), class: 'btn btn-danger' %>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/admin/users/users/_modal_revert.html.erb
<!-- Modal -->
<div class="modal fade" id="revertModal" tabindex="-1" role="dialog" aria-labelledby="revertModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :user, url: revert_removal_admin_users_user_path, method: :post do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="revertModalLabel"><%= t('admin.users.users.revert-modal.title') %></h4>
        </div>
        <div class="modal-body">
            <%= simple_format t("admin.users.users.revert-modal.notice") %>
        </div>
        <div class="modal-footer">
          <%= button_tag t('admin.users.users.revert-modal.close'), class: 'btn btn-default', 'type': 'button', 'data-dismiss': "modal" %>
          <%= button_tag t('admin.users.users.revert-modal.revert'), class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
  </div>
</div>