config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end

  root 'home#index'

  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'


  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'

  namespace :admin do
    resources :dashboard, only: [:index]

    namespace :users do

      resources :users, param: :username do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end

        member do
          post 'revert_removal', as: :revert_removal
          post 'block', as: :block
          post 'revert_block', as: :revert_block
          post 'suspect', as: :suspect
          post 'revert_suspect', as: :revert_suspect
        end
      end

      resources :filters

      scope(':username') do
        resources :dashboard, only: [:index]

        resources :preferences, only: [:index]

        resources :notifications, only: [:index]

        resources :permissions, only: [:index]

        resources :logs, only: [:index, :show]
      end
    end

    scope module: 'sites' do

      resources :sites, param: :site_uid

      scope('sites/:site_uid') do
        patch 'edit', to: 'sites#update', as: :site_update

        resources :api_keys
        resources :trusted_domains
      end

    end

    # resources :settings, only: [:index]
    get 'settings/index', as: :settings
    post 'settings/update', as: :update_settings

  end

  namespace :users do

    get 'sessions/new'

    get 'user/edit' => 'users#edit', as: :edit

    patch 'user' => 'users#update', as: :update

    delete 'user' => 'users#destroy', as: :destroy

    resources :users, except: [:show, :edit, :update, :destroy] do
      collection do
        get 'check_username', as: :check_username
      end
    end

    # /!\ order has importance here
    # if we want default actions  not to be considered as a username
    # please let this line after other 'users' routes
    get 'user/:username' => 'users#show', as: :show


    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]

    resources :preferences, only: [:index]

    resources :notifications, only: [:index] do
      collection do
        get 'unread_all'
      end
    end
  end # namespace users

  #omniauth
  match '/auth/:provider/callback', to: 'users/omniauth#callback', via: :all
  match '/auth/failure', to: 'users/omniauth#failure', via: :all
  match '/auth/:token', to: 'users/omniauth#complete_profile', via: :get, as: :auth_complete_profile
  match '/auth/:token', to: 'users/omniauth#finalize', via: :post, as: :auth_finalize

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          put :update
          get '/show' => 'users#show'
        end
      end
      resources :tokens, only: [:create] do
        collection do
          put :update
        end
      end
      resources :oauth_providers, only: [:index]
      resources :conversations, only: [:show], param: :identifier
    end #v1
  end # namespace api

  namespace :client do
    get '/' =>'home#index', as: :home
  end
end

app/views/layouts/admin/_nav_bar.html.erb
<ul id="main-nav" class="nav nav-pills">
  <li class="nav-item">
    <%= active_link_to t('admin.links.dashboard.index'), admin_dashboard_index_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= active_link_to t('admin.links.users.index'), admin_users_users_path, :class => 'nav-link', :active => /\/users\// %>
  </li>
  <li class="nav-item">
    <%= active_link_to t('admin.links.sites.index'), admin_sites_path, :class => 'nav-link', :active => /\/sites\// %>
  </li>
  <li class="nav-item">
    <%= active_link_to t('admin.links.settings.index'), admin_settings_path, :class => 'nav-link', :active => /admin\/settings\// %>
  </li>
</ul>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= render 'layouts/metas' %>
 
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content container">
      <%= render 'layouts/admin/nav_bar' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/admin/sites.html.erb
<% content_for :header do %>
    <%= stylesheet_link_tag 'admin/sites/sites' %>
<% end %>

<% content_for :content do %>
<div class="container">

  <div class="row">
    <div class="col-md-2">
      <%= render partial: 'admin/sites/shared/primary_sidebar', locals: { sites: @sites } %>
    </div>
    <div class="col-md-10">
      <div class="row">
        <%= render 'admin/sites/shared/nav_bar' %>
      </div>

      <div class="row tab-content">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<%= render 'admin/sites/sites/modal_new_site' %>
<% end %>
<%= render template: "layouts/admin/admin" %>