config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end

  root 'home#index'

  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'


  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'

  namespace :admin do
    resources :dashboard, only: [:index]

    namespace :users do

      resources :users, param: :username do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end

        member do
          post 'revert_removal', as: :revert_removal
          post 'block', as: :block
          post 'revert_block', as: :revert_block
          post 'suspect', as: :suspect
          post 'revert_suspect', as: :revert_suspect
        end
      end

      resources :filters

      scope(':username') do
        resources :dashboard, only: [:index]

        resources :preferences, only: [:index]

        resources :notifications, only: [:index]

        resources :permissions, only: [:index]

        resources :logs, only: [:index, :show]
      end
    end

    scope module: 'sites' do

      resources :sites, param: :site_uid

      scope('sites/:site_uid') do
        patch 'edit', to: 'sites#update', as: :site_update

        resources :api_keys
        resources :trusted_domains
      end

    end

    # resources :settings, only: [:index]
    get 'settings/index', as: :settings
    post 'settings/update', as: :update_settings

  end

  namespace :users do

    get 'sessions/new'

    get 'user/edit' => 'users#edit', as: :edit

    patch 'user' => 'users#update', as: :update

    delete 'user' => 'users#destroy', as: :destroy

    resources :users, except: [:show, :edit, :update, :destroy] do
      collection do
        get 'check_username', as: :check_username
      end
    end

    # /!\ order has importance here
    # if we want default actions  not to be considered as a username
    # please let this line after other 'users' routes
    get 'user/:username' => 'users#show', as: :show


    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]

    resources :preferences, only: [:index]

    resources :notifications, only: [:index] do
      collection do
        get 'unread_all'
      end
    end
  end # namespace users

  #omniauth
  match '/auth/:provider/callback', to: 'users/omniauth#callback', via: :all
  match '/auth/failure', to: 'users/omniauth#failure', via: :all
  match '/auth/:token', to: 'users/omniauth#complete_profile', via: :get, as: :auth_complete_profile
  match '/auth/:token', to: 'users/omniauth#finalize', via: :post, as: :auth_finalize

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          put :update
          get '/show' => 'users#show'
        end
      end
      resources :tokens, only: [:create] do
        collection do
          put :update
        end
      end
      resources :oauth_providers, only: [:index]
      resources :conversations, only: [:show], param: :identifier
    end #v1
  end # namespace api

  namespace :client do
    get '/' =>'home#index', as: :home
  end
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  @@DEFAULT_SETTING_ROOT = Rails.root.join('config', 'settings')
  @@defaults = {}

  def self.load_default_settings
    Dir["#{@@DEFAULT_SETTING_ROOT}/*.yml"].each do |file|
      basename = File.basename(file, ".yml")
      conf = load_yml_from_file(file)

      create_section_settings(basename, conf)
    end
  end


  def self.create_section_settings(section_name, hash )
    hash.each do |key, value|
      @@defaults["#{section_name}.#{key}"] = value
    end
  end

  def self.default_exists?(key)
    @@defaults.key?(key)
  end

  def self.[](var_name)
    if var = object(var_name)
      val = var.value
    else
      val = @@defaults[var_name]
    end
    val
  end

  private


  def self.load_yml_from_file(file)
    YAML::load( File.open(file) )
  end
end

# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string           not null
#  value      :text
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_settings_on_thing_type_and_thing_id_and_var  (thing_type,thing_id,var) UNIQUE
#

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController
  include SettingsHelper

  def index
    @settings = Setting.get
  end

  def update
    permitted_settings.each do |key, value|
      Setting[key] = value
    end
    flash[:info] = I18n.t('settings.index.infos.reload')
    redirect_to admin_settings_url
  end

  private

  def permitted_settings
    params.require(:settings).tap do |whitelisted|
      Setting.defaults.keys.each do |k|
        if params[:settings].has_key?(k) && params[:settings][k].to_json != Setting[k].to_json
          whitelisted[k] = params[:settings][k]
        end
      end
    end
  end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper

  def setting(*path)
    value = Setting[path.shift]

    return if value.nil?
    return value if path.empty?

    last_key = path.pop

    path.each do |k|
      value = value.fetch(k, {})
    end

    value.fetch(last_key, nil)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper

  def setting(*path)
    value = Setting[path.shift]

    return if value.nil?
    return value if path.empty?

    last_key = path.pop

    path.each do |k|
      value = value.fetch(k, {})
    end

    value.fetch(last_key, nil)
  end
end

app/views/admin/settings/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <ul id="secondary-nav" class="nav nav-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#auth" role="tab"><%= t 'settings.index.tabs.authentication' %></a>
        </li>
      </ul>

      <%= form_with url: admin_update_settings_path do |form| %>
        <div class="tab-content">
          <div class="tab-pane active" id="auth" role="tabpanel">
            <div class="container">
              <h6>Facebook</h6>
              <hr/>
              <div class="container">
                <div class="form-group clearfix">
                  <label class="col-form-label-sm col-md-2">Activate</label>
                  <div class="col-md-10">
                    <div class="btn-group" data-toggle="buttons">
                      <label class="btn btn-primary btn-sm <%= 'active' if setting('global.auth', 'facebook', 'enable') == '1' %>">
                        <%= form.radio_button 'settings[global.auth][facebook][enable]',
                                              '1',
                                              :checked => setting('global.auth', 'facebook', 'enable') == '1',
                                              autocomplete: 'off' %>Yes
                      </label>
                      <label class="btn btn-primary btn-sm <%= 'active' if setting('global.auth', 'facebook', 'enable') != '1' %>">
                        <%= form.radio_button 'settings[global.auth][facebook][enable]',
                                              '0',
                                              :checked => setting('global.auth', 'facebook', 'enable') != '1',
                                              autocomplete: 'off' %>No
                      </label>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-form-label-sm col-md-2">App Id</label>
                  <div class="col-md-10">
                    <%= form.text_field 'settings[global.auth][facebook][app_id]',
                                        class: 'form-control form-control-sm',
                                        placeholder: 'App id',
                                        value: setting('global.auth', 'facebook', 'app_id'),
                                        autocomplete: 'off'
                    %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-form-label-sm col-md-2">Secret key</label>
                  <div class="col-md-10">
                    <%= form.text_field 'settings[global.auth][facebook][secret_key]',
                                        class: 'form-control form-control-sm',
                                        placeholder: 'Secret key',
                                        value: setting('global.auth', 'facebook', 'secret_key'),
                                        autocomplete: 'off'
                    %>
                  </div>
                </div>
              </div>
              <h6>Google</h6>
              <hr/>
              <div class="container">
                <div class="form-group clearfix">
                  <label class="col-form-label-sm col-md-2">Activate</label>
                  <div class="col-md-10">
                    <div class="btn-group" data-toggle="buttons">
                      <label class="btn btn-primary btn-sm <%= 'active' if setting('global.auth', 'google', 'enable') == '1' %>">
                        <%= form.radio_button 'settings[global.auth][google][enable]',
                                              '1',
                                              :checked => setting('global.auth', 'google', 'enable') == '1',
                                              autocomplete: 'off' %>Yes
                      </label>
                      <label class="btn btn-primary btn-sm <%= 'active' if setting('global.auth', 'google', 'enable') != '1' %>">
                        <%= form.radio_button 'settings[global.auth][google][enable]',
                                              '0',
                                              :checked => setting('global.auth', 'google', 'enable') != '1',
                                              autocomplete: 'off' %>No
                      </label>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-form-label-sm col-md-2">Client id</label>
                  <div class="col-md-10">
                    <%= form.text_field 'settings[global.auth][google][client_id]',
                                        class: 'form-control form-control-sm',
                                        placeholder: 'Client id',
                                        value: setting('global.auth', 'google', 'client_id'),
                                        autocomplete: 'off'
                    %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-form-label-sm col-md-2">Client secret</label>
                  <div class="col-md-10">
                    <%= form.text_field 'settings[global.auth][google][client_secret]',
                                        class: 'form-control form-control-sm',
                                        placeholder: 'Client secret',
                                        value: setting('global.auth', 'google', 'client_secret'),
                                        autocomplete: 'off'
                    %>
                  </div>
                </div>
              </div>
              <h6>Twitter</h6>
              <hr/>
              <div class="container">
                <div class="form-group clearfix">
                  <label class="col-form-label-sm col-md-2">Activate</label>
                  <div class="col-md-10">
                    <div class="btn-group" data-toggle="buttons">
                      <label class="btn btn-primary btn-sm <%= 'active' if setting('global.auth', 'twitter', 'enable') == '1' %>">
                        <%= form.radio_button 'settings[global.auth][twitter][enable]',
                                              '1',
                                              :checked => setting('global.auth', 'twitter', 'enable') == '1',
                                              autocomplete: 'off' %>Yes
                      </label>
                      <label class="btn btn-primary btn-sm <%= 'active' if setting('global.auth', 'twitter', 'enable') != '1' %>">
                        <%= form.radio_button 'settings[global.auth][twitter][enable]',
                                              '0',
                                              :checked => setting('global.auth', 'twitter', 'enable') != '1',
                                              autocomplete: 'off' %>No
                      </label>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-form-label-sm col-md-2">Api key</label>
                  <div class="col-md-10">
                    <%= form.text_field 'settings[global.auth][twitter][consumer_key]',
                                        class: 'form-control form-control-sm',
                                        placeholder: 'Consumer key',
                                        value: setting('global.auth', 'twitter', 'consumer_key'),
                                        autocomplete: 'off'
                    %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-form-label-sm col-md-2">Api secret</label>
                  <div class="col-md-10">
                    <%= form.text_field 'settings[global.auth][twitter][consumer_secret]',
                                        class: 'form-control form-control-sm',
                                        placeholder: 'Consumer secret',
                                        value: setting('global.auth', 'twitter', 'consumer_secret'),
                                        autocomplete: 'off'
                    %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row row-section">
          <div class="col-md-6 offset-md-3">
            <%= form.submit t('user.form.edit.submit'), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>