config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end

  root 'home#index'

  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'


  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'

  namespace :admin do
    resources :dashboard, only: [:index]

    namespace :users do

      resources :users, param: :username do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end

        member do
          post 'revert_removal', as: :revert_removal
          post 'block', as: :block
          post 'revert_block', as: :revert_block
          post 'suspect', as: :suspect
          post 'revert_suspect', as: :revert_suspect
        end
      end

      resources :filters

      scope(':username') do
        resources :dashboard, only: [:index]

        resources :preferences, only: [:index]

        resources :notifications, only: [:index]

        resources :permissions, only: [:index]

        resources :logs, only: [:index, :show]
      end
    end

    scope module: 'sites' do

      resources :sites, param: :site_uid

      scope('sites/:site_uid') do
        patch 'edit', to: 'sites#update', as: :site_update

        resources :api_keys
        resources :trusted_domains
      end

    end

    # resources :settings, only: [:index]
    get 'settings/index', as: :settings
    post 'settings/update', as: :update_settings

  end

  namespace :users do

    get 'sessions/new'

    get 'user/edit' => 'users#edit', as: :edit

    patch 'user' => 'users#update', as: :update

    delete 'user' => 'users#destroy', as: :destroy

    resources :users, except: [:show, :edit, :update, :destroy] do
      collection do
        get 'check_username', as: :check_username
      end
    end

    # /!\ order has importance here
    # if we want default actions  not to be considered as a username
    # please let this line after other 'users' routes
    get 'user/:username' => 'users#show', as: :show


    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]

    resources :preferences, only: [:index]

    resources :notifications, only: [:index] do
      collection do
        get 'unread_all'
      end
    end
  end # namespace users

  #omniauth
  match '/auth/:provider/callback', to: 'users/omniauth#callback', via: :all
  match '/auth/failure', to: 'users/omniauth#failure', via: :all
  match '/auth/:token', to: 'users/omniauth#complete_profile', via: :get, as: :auth_complete_profile
  match '/auth/:token', to: 'users/omniauth#finalize', via: :post, as: :auth_finalize

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          put :update
          get '/show' => 'users#show'
        end
      end
      resources :tokens, only: [:create] do
        collection do
          put :update
        end
      end
      resources :oauth_providers, only: [:index]
      resources :conversations, only: [:show], param: :identifier
    end #v1
  end # namespace api

  namespace :client do
    get '/' =>'home#index', as: :home
  end
end

app/models/site.rb
class Site < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3 }
  validates :uid, presence: true, uniqueness: { case_sensitive: false }

  before_validation :generate_uid, if: :new_record?
  after_create :create_default_api_key

  has_many :api_keys, dependent: :destroy
  has_many :trusted_domains, dependent: :destroy
  has_many :conversations, dependent: :destroy


  scope :oldest_first, -> { order( created_at: :desc ) }

  private

  def generate_uid
    self.uid = name.parameterize if name.present?
  end

  def create_default_api_key
    api_keys.create(label: 'default')
  end
end

# == Schema Information
#
# Table name: sites
#
#  id         :integer          not null, primary key
#  name       :string
#  uid        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/admin/sites/api_keys_controller.rb
class Admin::Sites::ApiKeysController < Admin::AdminController
  include Admin::Sites::SitesHelper

  before_action :identify_site
  before_action :include_sites
  before_action :set_api_key, only: [:destroy]

  layout 'admin/sites'

  def index
    render locals: { site: @site, sites: @sites }
  end

  def create
    @api_key = @site.api_keys.create(api_key_params)
  end

  def destroy
    @api_key.destroy
  end

  private

  def set_api_key
    @api_key = @site.api_keys.find_by_id(params[:id])
  end

  def api_key_params
    params.require(:api_key).permit( :label )
  end
end

app/controllers/admin/sites/sites_controller.rb
class Admin::Sites::SitesController < Admin::AdminController

  include Admin::Sites::SitesHelper

  before_action :identify_site, except: [ :index, :new, :create ]
  before_action :include_sites, only: [ :show, :edit, :update ]

  layout 'admin/sites'

  def index
    redirect_to admin_site_path(Site.first.uid)
  end

  def show
    render locals: { sites: @sites }
  end

  def new

  end

  def create
    @site = Site.create(create_params)

    flash.now[:success] = t 'admin.sites.sites.notice.success.created' if @site.errors.empty?

    render locals: { site: @site }
  end

  def edit
    render_edit
  end

  def update
    if @site.update_attributes(update_params)
      flash[:success] = t 'admin.sites.sites.notice.success.updated'
      redirect_to :edit_admin_site
    else
      render_edit
    end
  end

  private

  def render_edit
    render :edit, locals: { site: @site, sites: @sites }
  end


  def create_params
    params.require(:site).permit(
        :name
    )
  end

  def update_params
    params.require(:site).permit(
        :name
    )
  end

end

app/controllers/admin/sites/trusted_domains_controller.rb
class Admin::Sites::TrustedDomainsController < Admin::AdminController
  include Admin::Sites::SitesHelper

  before_action :identify_site
  before_action :include_sites
  before_action :set_trusted_domain, only: [:destroy]

  layout 'admin/sites'

  def index
    render locals: { site: @site, sites: @sites }
  end

  def create
    @trusted_domain = @site.trusted_domains.create(trusted_domain_params)
  end

  def destroy
    @trusted_domain.destroy
  end

  private

  def set_trusted_domain
    @trusted_domain = @site.trusted_domains.find_by_id(params[:id])
  end

  def trusted_domain_params
    params.require(:trusted_domain).permit( :domain )
  end
end

app/helpers/admin/sites/api_keys_helper.rb
module Admin::Sites::ApiKeysHelper
end

app/helpers/admin/sites/sites_helper.rb
module Admin::Sites::SitesHelper

  def identify_site
    @site = Site.where(uid: params[:site_uid]).first

    redirect_to :admin_dashboard_index if @site.nil?
  end


  def include_sites
    @sites = Site.oldest_first
  end
end

app/views/admin/sites/sites/_modal_new_site.html.erb
<!-- Modal -->
<div class="modal fade" id="newSiteModal" tabindex="-1" role="dialog" aria-labelledby="newSiteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :site, url: :admin_sites ,remote:true do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="newSiteModalLabel"><%= t('admin.sites.sites.new.title') %></h4>
          </div>
          <div class="modal-body">

            <div class="row">
              <div class="col-md-12">
                <%= f.label :name %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <%= f.text_field :name, class: 'form-control', value: '' %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= button_tag t('admin.sites.sites.new.close'), class: 'btn btn-default', 'type': 'button', 'data-dismiss': "modal" %>
            <%= f.button t('admin.sites.sites.new.submit'), class: 'btn btn-primary' %>
          </div>
      <% end %>
      </div>
</div>

app/views/admin/sites/sites/create.js.erb
<% if site.errors.any? %>
 $('#newSiteModal #error_explanation').remove();
 $('#newSiteModal .modal-body').prepend("<%= j  render 'shared/error_messages', object: site %>");
<% else %>
 window.location = '<%= edit_admin_site_path(@site.uid) %>'
 $('#newSiteModal form')[0].reset();
<% end %>

app/views/admin/sites/sites/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <%= render 'admin/sites/shared/settings_nav', site: site %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 offset-md-3">
        <%= form_for [:sites, site], url: admin_site_update_path do |f| %>
          <%= render 'shared/error_messages', object: f.object %>


          <div class="row">
            <div class="col-md-12">
              <%= f.label :name %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>


          <div class="row">
            <div class="col-md-12">
              <%= f.label :uid %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <%= f.text_field :uid, class: 'form-control', readonly: ''%>
            </div>
          </div>

          <div class="row row-section">
            <div class="col-md-12">
              <%= f.submit  t('admin.sites.sites.edit.submit'), class: "btn btn-primary" %>
            </div>
          </div>

      <% end %>

    </div>
  </div>

</div>